extends RefCounted
class_name TalentTreeData

# -------------------------------------------------------
# Talent Tree Definitions
# Each node: id, display name, description, branch, cost (combined Food+Gold),
# prereq node id (or "" for none), and a min_stage gate (0 = no gate).
# Ordered within each branch from cheapest/earliest to most powerful/latest,
# mirroring normal game progression — big unlocks (Transcendent quality,
# 3-choice recruiting, Hero's Resolve) sit at the end of their chains.
# -------------------------------------------------------

const BRANCHES = ["Gear", "Buildings", "Recruiting", "Combat", "Economy", "Standalone"]

const NODES = {
	# --- GEAR ---
	"gear_sharper_eye": {
		"name": "Sharper Eye", "branch": "Gear", "cost": 100, "prereq": "", "min_stage": 0,
		"desc": "Common and Rare gear has a chance to roll one extra stat.",
	},
	"gear_set_seeker": {
		"name": "Set Seeker", "branch": "Gear", "cost": 150, "prereq": "gear_sharper_eye", "min_stage": 0,
		"desc": "Increases the chance gear drops as part of a themed set.",
	},
	"gear_awakened_quality": {
		"name": "Awakened Quality", "branch": "Gear", "cost": 250, "prereq": "gear_set_seeker", "min_stage": 3,
		"desc": "Unlocks a chance for Epic/Legendary gear to roll Awakened quality \\u2014 stats above the normal ceiling.",
	},
	"gear_ascendant_quality": {
		"name": "Ascendant Quality", "branch": "Gear", "cost": 450, "prereq": "gear_awakened_quality", "min_stage": 6,
		"desc": "Unlocks a chance for Epic/Legendary gear to roll Ascendant quality, rarer and stronger than Awakened.",
	},
	"gear_transcendent_quality": {
		"name": "Transcendent Quality", "branch": "Gear", "cost": 800, "prereq": "gear_ascendant_quality", "min_stage": 10,
		"desc": "Unlocks a rare chance for Legendary gear to roll Transcendent quality \\u2014 the absolute pinnacle.",
	},

	# --- BUILDINGS ---
	"buildings_efficient_construction": {
		"name": "Efficient Construction", "branch": "Buildings", "cost": 100, "prereq": "", "min_stage": 0,
		"desc": "Reduces the resource cost of building and upgrading by 25%.",
	},
	"buildings_expanded_lots": {
		"name": "Expanded Lots", "branch": "Buildings", "cost": 250, "prereq": "buildings_efficient_construction", "min_stage": 0,
		"desc": "Raises the maximum buildings per zone from 2 to 3.",
	},
	"buildings_reinforced_towers": {
		"name": "Reinforced Towers", "branch": "Buildings", "cost": 200, "prereq": "buildings_efficient_construction", "min_stage": 0,
		"desc": "Watchtowers grant +2 turns of attack warning instead of +1.",
	},
	"buildings_wider_reach": {
		"name": "Wider Reach", "branch": "Buildings", "cost": 350, "prereq": "buildings_expanded_lots", "min_stage": 0,
		"desc": "Forge and Shrine bonuses extend two zones out instead of just adjacent.",
	},

	# --- RECRUITING ---
	"recruiting_talent_scout": {
		"name": "Talent Scout", "branch": "Recruiting", "cost": 100, "prereq": "", "min_stage": 0,
		"desc": "Reduces the resource cost of recruiting a new unit by 20%.",
	},
	"recruiting_pick_of_the_litter": {
		"name": "Pick of the Litter", "branch": "Recruiting", "cost": 300, "prereq": "recruiting_talent_scout", "min_stage": 4,
		"desc": "The recruit shop offers a choice of 2 random units instead of 1.",
	},
	"recruiting_cream_of_the_crop": {
		"name": "Cream of the Crop", "branch": "Recruiting", "cost": 600, "prereq": "recruiting_pick_of_the_litter", "min_stage": 8,
		"desc": "The recruit shop offers a choice of 3 random units instead of 2.",
	},

	# --- COMBAT ---
	"combat_hardened_ranks": {
		"name": "Hardened Ranks", "branch": "Combat", "cost": 150, "prereq": "", "min_stage": 0,
		"desc": "All troops gain a small flat HP bonus.",
	},
	"combat_sharpened_blades": {
		"name": "Sharpened Blades", "branch": "Combat", "cost": 150, "prereq": "", "min_stage": 0,
		"desc": "All troops gain a small flat attack bonus.",
	},
	"combat_forced_march": {
		"name": "Forced March", "branch": "Combat", "cost": 200, "prereq": "combat_hardened_ranks", "min_stage": 0,
		"desc": "Troops marching between zones travel 50% faster.",
	},
	"combat_heros_resolve": {
		"name": "Hero's Resolve", "branch": "Combat", "cost": 250, "prereq": "combat_sharpened_blades", "min_stage": 5,
		"desc": "Your dungeon hero specifically gains an additional HP and attack bonus.",
	},

	# --- ECONOMY ---
	"economy_bountiful_harvest": {
		"name": "Bountiful Harvest", "branch": "Economy", "cost": 100, "prereq": "", "min_stage": 0,
		"desc": "Increases Food generated by Farms each turn.",
	},
	"economy_steady_coffers": {
		"name": "Steady Coffers", "branch": "Economy", "cost": 100, "prereq": "", "min_stage": 0,
		"desc": "Increases Gold generated by Barracks each turn.",
	},
	"economy_trade_routes": {
		"name": "Trade Routes", "branch": "Economy", "cost": 300, "prereq": "economy_bountiful_harvest", "min_stage": 0,
		"desc": "Owned zones generate a small passive Gold trickle even without Farm or Barracks built.",
	},

	# --- STANDALONE ---
	"diplomatic_tongue": {
		"name": "Diplomatic Tongue", "branch": "Standalone", "cost": 200, "prereq": "", "min_stage": 3,
		"desc": "Conquest battles are slightly easier \\u2014 the zone's defenders fight at reduced strength.",
	},
}

# Returns true if the node's prerequisite (if any) is already unlocked.
static func prereq_met(node_id: String) -> bool:
	var prereq = NODES[node_id]["prereq"]
	if prereq == "":
		return true
	return PlayerInventory.unlocked_talents.get(prereq, false)

# Returns true if the node's stage gate (if any) is satisfied.
static func stage_met(node_id: String) -> bool:
	var min_stage = NODES[node_id]["min_stage"]
	if min_stage <= 0:
		return true
	return PlayerInventory.current_stage >= min_stage

# Returns true if the node can currently be purchased (not already owned,
# prereq met, stage met, affordable).
static func can_purchase(node_id: String) -> bool:
	if PlayerInventory.unlocked_talents.get(node_id, false):
		return false
	if not prereq_met(node_id):
		return false
	if not stage_met(node_id):
		return false
	var cost = NODES[node_id]["cost"]
	return PlayerInventory.can_afford({"food": 0, "gold": cost})

# Purchases a node: deducts cost, marks it unlocked, and applies any
# immediate one-time effects (most effects are read live via
# unlocked_talents.get(...) elsewhere, but a few need a direct value set
# at purchase time, like Expanded Lots raising max_buildings_per_zone).
static func purchase(node_id: String) -> bool:
	if not can_purchase(node_id):
		return false

	var cost = NODES[node_id]["cost"]
	PlayerInventory.spend_resources({"food": 0, "gold": cost})
	PlayerInventory.unlocked_talents[node_id] = true

	# Direct one-time effects
	if node_id == "buildings_expanded_lots":
		PlayerInventory.max_buildings_per_zone = 3

	# Gear quality unlocks also flip the legacy talents dict that
	# gear_generator.gd reads directly, with reasonable default chances.
	if node_id == "gear_awakened_quality":
		PlayerInventory.talents["awakened_unlock"] = true
		PlayerInventory.talents["awakened_chance_epic"] = 0.08
		PlayerInventory.talents["awakened_chance_legendary"] = 0.15
	elif node_id == "gear_ascendant_quality":
		PlayerInventory.talents["ascendant_unlock"] = true
		PlayerInventory.talents["ascendant_chance_epic"] = 0.03
		PlayerInventory.talents["ascendant_chance_legendary"] = 0.08
	elif node_id == "gear_transcendent_quality":
		PlayerInventory.talents["transcendent_unlock"] = true
		PlayerInventory.talents["transcendent_chance"] = 0.02

	return true

# Returns all node IDs belonging to a branch, in their defined (progression) order.
static func get_branch_nodes(branch: String) -> Array:
	var result = []
	for node_id in NODES:
		if NODES[node_id]["branch"] == branch:
			result.append(node_id)
	return result
